# Generated by Django 2.1.8 on 2019-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsauth', '0003_auto_20190507_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='white',
            name='method',
            field=models.CharField(default='GET', max_length=16),
        ),
    ]
