# Generated by Django 2.1.8 on 2019-05-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsauth', '0004_white_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ordinaryadmin',
            field=models.BooleanField(default=False),
        ),
    ]
