# Generated by Django 2.1.8 on 2019-05-03 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooperation_models', models.CharField(max_length=32, verbose_name='合作形式')),
                ('code', models.CharField(max_length=32, verbose_name='公司代码')),
                ('area', models.CharField(max_length=32, verbose_name='区域')),
                ('block', models.CharField(max_length=32, verbose_name='大楼')),
                ('floor', models.CharField(max_length=32, verbose_name='楼层')),
                ('addr', models.CharField(max_length=128, verbose_name='地址')),
                ('rebate', models.TextField(verbose_name='返拥')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'db_table': 'rms_company',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='岗位名称')),
            ],
        ),
        migrations.CreateModel(
            name='JobDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.IntegerField(choices=[(1, '国内'), (2, '外籍')], default=1)),
                ('nums', models.CharField(max_length=32, verbose_name='需求数量')),
                ('work', models.TextField(verbose_name='岗位职责')),
                ('need', models.TextField(verbose_name='任职资格')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '男女不限')], verbose_name='性别')),
                ('edu', models.CharField(max_length=64, verbose_name='学历')),
                ('work_years', models.CharField(max_length=64, verbose_name='工作年限')),
                ('essential_condition', models.TextField(verbose_name='必备条件')),
                ('recruitment_way', models.CharField(max_length=64, verbose_name='招聘渠道')),
                ('probation_salary', models.CharField(max_length=64, verbose_name='试用期薪资')),
                ('salary', models.CharField(max_length=64, verbose_name='薪资')),
                ('salary_method', models.TextField(verbose_name='薪资发放方式')),
                ('performance', models.TextField(verbose_name='提成绩效')),
                ('work_time', models.CharField(max_length=64, verbose_name='工作时间')),
                ('holiday', models.CharField(max_length=64, verbose_name='每月休假')),
                ('job_subsidy', models.TextField(verbose_name='岗位补贴')),
                ('life_subsidy', models.TextField(verbose_name='生活补贴')),
                ('dorm', models.CharField(max_length=64, verbose_name='宿舍条件')),
                ('welfare', models.TextField(verbose_name='其他福利')),
                ('note', models.TextField(verbose_name='备注')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '岗位要求',
                'verbose_name_plural': '岗位要求',
                'db_table': 'rms_jobdemand',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='渠道名')),
                ('link_man', models.CharField(max_length=32, verbose_name='联系人')),
                ('contact_way', models.CharField(max_length=64, verbose_name='联系方式')),
            ],
            options={
                'verbose_name': '中介',
                'verbose_name_plural': '中介',
            },
        ),
        migrations.CreateModel(
            name='UrgencyJobDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebate', models.CharField(max_length=64, verbose_name='返拥')),
                ('work', models.TextField(verbose_name='岗位职责')),
                ('need', models.TextField(verbose_name='任职资格')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '男女不限')], verbose_name='性别')),
                ('edu', models.CharField(max_length=64, verbose_name='学历')),
                ('essential_condition', models.TextField(verbose_name='必备条件')),
                ('salary', models.CharField(max_length=64, verbose_name='薪资')),
                ('performance', models.TextField(verbose_name='提成绩效')),
                ('work_time', models.CharField(max_length=64, verbose_name='工作时间')),
                ('work_addr', models.CharField(max_length=64, verbose_name='工作地点')),
                ('status', models.CharField(max_length=64, verbose_name='状态')),
                ('note', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '限时悬赏',
                'verbose_name_plural': '限时悬赏',
                'db_table': 'rms_urgencyjobdemand',
            },
        ),
    ]
