# Generated by Django 2.1.8 on 2019-05-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsManager', '0002_auto_20190503_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id'], 'verbose_name': '公司', 'verbose_name_plural': '公司'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='jobdemand',
            options={'ordering': ['-id'], 'verbose_name': '岗位要求', 'verbose_name_plural': '岗位要求'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentway',
            options={'ordering': ['-id'], 'verbose_name': '中介', 'verbose_name_plural': '中介'},
        ),
        migrations.AlterModelOptions(
            name='urgencyjobdemand',
            options={'ordering': ['-id'], 'verbose_name': '限时悬赏', 'verbose_name_plural': '限时悬赏'},
        ),
    ]
