# Generated by Django 2.1.8 on 2019-05-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='entry_percent',
            field=models.CharField(max_length=32),
        ),
    ]
