# Generated by Django 2.1.8 on 2019-05-12 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rmsManager', '0004_auto_20190507_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'rms_interview',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewedCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'rms_interviewed_company',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'rms_region',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'rms_schedule',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_url', models.UUIDField(null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '待面试'), (1, '待入职'), (2, '办理签证'), (3, '待分配'), (4, '到岗'), (5, '跳票'), (6, '已放弃'), (7, '离职')])),
                ('expect_job', models.CharField(blank=True, max_length=128, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('underway', models.BooleanField(default=False)),
                ('admit_date', models.DateTimeField(blank=True, null=True)),
                ('admit_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmsManager.Company')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmsManager.RecruitmentWay')),
                ('interviewed_company', models.ManyToManyField(to='rmstalent.InterviewedCompany')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmsManager.Job')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmstalent.Region')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rms_talent',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='status',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_list', to='rmstalent.Talent'),
        ),
    ]
